services:
  app:
    container_name: session-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    container_name: session-db
    image: postgres:15.3
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    env_file:
      - .env
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  redis:
    container_name: session-redis
    image: redis:6.0.20-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: